{% set name = "cppyythonizations" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flatsurf/cppyythonizations/releases/download/{{ version }}/cppyythonizations-{{ version }}.tar.gz
  sha256: df5c3c63d14b6c77f100dd6849fd3ef79516c74f792245aafd707e0a4d7d95bc

build:
  noarch: python
  number: 0

requirements:
  build:
    - automake
    - coreutils
    - make
  host:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - cppyy

test:
  imports:
    - cppyythonizations
    - cppyythonizations.operators.arithmetic
    - cppyythonizations.operators.order
    - cppyythonizations.vector
    - cppyythonizations.tuple
    - cppyythonizations.util

about:
  home: https://github.com/flatsurf/cppyythonizations
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'A collection of Pythonizations for cppyy.'
  description: |
    A collection of Pythonizations for cppyy to work around known limitations
    of cppyy or provide some reusable extensions such as Python pickling of
    C++ classes.
  dev_url: https://github.com/flatsurf/cppyythonizations

extra:
  recipe-maintainers:
    - saraedum
