{% set name = "cppyythonizations" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flatsurf/cppyythonizations/releases/download/{{ version }}/cppyythonizations-{{ version }}.tar.gz
  sha256: fc0a6cf2ce59e48bb5b540b6d019b2356f093db17ecb109ec10cfcd35b27dddc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - cppyy

test:
  imports:
    - cppyythonizations
    - cppyythonizations.operators.arithmetic
    - cppyythonizations.operators.order
    - cppyythonizations.vector
    - cppyythonizations.tuple
    - cppyythonizations.util

about:
  home: https://github.com/flatsurf/cppyythonizations
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'A collection of Pythonizations for cppyy.'
  description: |
    A collection of Pythonizations for cppyy to work around known limitations
    of cppyy or provide some reusable extensions such as Python pickling of
    C++ classes.
  dev_url: https://github.com/flatsurf/cppyythonizations

extra:
  recipe-maintainers:
    - saraedum
