{% set name = "cppyythonizations" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flatsurf/cppyythonizations/releases/download/{{ version }}/cppyythonizations-{{ version }}.tar.gz
  sha256: 183b4ef396f1236b641c705021e1b4074a0eda76d698c08bd2674fdea88c9515

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - cppyy

test:
  requires:
    - python {{ python_min }}
  imports:
    - cppyythonizations
    - cppyythonizations.operators.arithmetic
    - cppyythonizations.operators.order
    - cppyythonizations.vector
    - cppyythonizations.tuple
    - cppyythonizations.util

about:
  home: https://github.com/flatsurf/cppyythonizations
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'A collection of Pythonizations for cppyy.'
  description: |
    A collection of Pythonizations for cppyy to work around known limitations
    of cppyy or provide some reusable extensions such as Python pickling of
    C++ classes.
  dev_url: https://github.com/flatsurf/cppyythonizations

extra:
  recipe-maintainers:
    - saraedum
